name: Deploy
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy plantuml-server.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install ssh-key
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}
        ssh-host: report.hufeifei.cn
    - name: Deploy Server
      run: |
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -t rsa report.hufeifei.cn >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa root@report.hufeifei.cn 'docker stop plantuml-server; \
        docker rm plantuml-server; \
        docker run -d -p 18080:8080 -e BASE_URL=plantuml --name plantuml-server plantuml/plantuml-server:jetty'
